language: python
python:
- 2.7
sudo: false
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- python bootstrap.py
- bin/buildout -N -t 3
script:
- bin/test
- bin/code-analysis
cache:
  directories:
  - eggs
